-- Migration 009 : Référentiel pays du monde (ISO 3166)

INSERT INTO ref_pays (code_iso2, code_iso3, nom_fr, nom_en, region_monde) VALUES
('AF','AFG','Afghanistan','Afghanistan','Asie du Sud'),
('ZA','ZAF','Afrique du Sud','South Africa','Afrique subsaharienne'),
('AL','ALB','Albanie','Albania','Europe du Sud'),
('DZ','DZA','Algérie','Algeria','Afrique du Nord'),
('DE','DEU','Allemagne','Germany','Europe occidentale'),
('AD','AND','Andorre','Andorra','Europe du Sud'),
('AO','AGO','Angola','Angola','Afrique subsaharienne'),
('AG','ATG','Antigua-et-Barbuda','Antigua and Barbuda','Caraïbes'),
('SA','SAU','Arabie Saoudite','Saudi Arabia','Moyen-Orient'),
('AR','ARG','Argentine','Argentina','Amérique du Sud'),
('AM','ARM','Arménie','Armenia','Asie de l''Ouest'),
('AU','AUS','Australie','Australia','Océanie'),
('AT','AUT','Autriche','Austria','Europe occidentale'),
('AZ','AZE','Azerbaïdjan','Azerbaijan','Asie de l''Ouest'),
('BS','BHS','Bahamas','Bahamas','Caraïbes'),
('BH','BHR','Bahreïn','Bahrain','Moyen-Orient'),
('BD','BGD','Bangladesh','Bangladesh','Asie du Sud'),
('BB','BRB','Barbade','Barbados','Caraïbes'),
('BE','BEL','Belgique','Belgium','Europe occidentale'),
('BZ','BLZ','Belize','Belize','Amérique centrale'),
('BJ','BEN','Bénin','Benin','Afrique subsaharienne'),
('BT','BTN','Bhoutan','Bhutan','Asie du Sud'),
('BY','BLR','Biélorussie','Belarus','Europe de l''Est'),
('BO','BOL','Bolivie','Bolivia','Amérique du Sud'),
('BA','BIH','Bosnie-Herzégovine','Bosnia and Herzegovina','Europe du Sud'),
('BW','BWA','Botswana','Botswana','Afrique subsaharienne'),
('BR','BRA','Brésil','Brazil','Amérique du Sud'),
('BN','BRN','Brunei','Brunei','Asie du Sud-Est'),
('BG','BGR','Bulgarie','Bulgaria','Europe de l''Est'),
('BF','BFA','Burkina Faso','Burkina Faso','Afrique subsaharienne'),
('BI','BDI','Burundi','Burundi','Afrique subsaharienne'),
('CV','CPV','Cap-Vert','Cape Verde','Afrique subsaharienne'),
('KH','KHM','Cambodge','Cambodia','Asie du Sud-Est'),
('CM','CMR','Cameroun','Cameroon','Afrique subsaharienne'),
('CA','CAN','Canada','Canada','Amérique du Nord'),
('CF','CAF','République centrafricaine','Central African Republic','Afrique subsaharienne'),
('CL','CHL','Chili','Chile','Amérique du Sud'),
('CN','CHN','Chine','China','Asie de l''Est'),
('CY','CYP','Chypre','Cyprus','Europe du Sud'),
('CO','COL','Colombie','Colombia','Amérique du Sud'),
('KM','COM','Comores','Comoros','Afrique subsaharienne'),
('CG','COG','Congo','Congo','Afrique subsaharienne'),
('CD','COD','République démocratique du Congo','Democratic Republic of the Congo','Afrique subsaharienne'),
('KP','PRK','Corée du Nord','North Korea','Asie de l''Est'),
('KR','KOR','Corée du Sud','South Korea','Asie de l''Est'),
('CR','CRI','Costa Rica','Costa Rica','Amérique centrale'),
('CI','CIV','Côte d''Ivoire','Ivory Coast','Afrique subsaharienne'),
('HR','HRV','Croatie','Croatia','Europe du Sud'),
('CU','CUB','Cuba','Cuba','Caraïbes'),
('DK','DNK','Danemark','Denmark','Europe du Nord'),
('DJ','DJI','Djibouti','Djibouti','Afrique de l''Est'),
('DM','DMA','Dominique','Dominica','Caraïbes'),
('EG','EGY','Égypte','Egypt','Afrique du Nord'),
('AE','ARE','Émirats arabes unis','United Arab Emirates','Moyen-Orient'),
('EC','ECU','Équateur','Ecuador','Amérique du Sud'),
('ER','ERI','Érythrée','Eritrea','Afrique de l''Est'),
('ES','ESP','Espagne','Spain','Europe du Sud'),
('EE','EST','Estonie','Estonia','Europe du Nord'),
('SZ','SWZ','Eswatini','Eswatini','Afrique subsaharienne'),
('US','USA','États-Unis','United States','Amérique du Nord'),
('ET','ETH','Éthiopie','Ethiopia','Afrique de l''Est'),
('FJ','FJI','Fidji','Fiji','Océanie'),
('FI','FIN','Finlande','Finland','Europe du Nord'),
('FR','FRA','France','France','Europe occidentale'),
('GA','GAB','Gabon','Gabon','Afrique subsaharienne'),
('GM','GMB','Gambie','Gambia','Afrique subsaharienne'),
('GE','GEO','Géorgie','Georgia','Asie de l''Ouest'),
('GH','GHA','Ghana','Ghana','Afrique subsaharienne'),
('GR','GRC','Grèce','Greece','Europe du Sud'),
('GD','GRD','Grenade','Grenada','Caraïbes'),
('GT','GTM','Guatemala','Guatemala','Amérique centrale'),
('GN','GIN','Guinée','Guinea','Afrique subsaharienne'),
('GW','GNB','Guinée-Bissau','Guinea-Bissau','Afrique subsaharienne'),
('GQ','GNQ','Guinée équatoriale','Equatorial Guinea','Afrique subsaharienne'),
('GY','GUY','Guyana','Guyana','Amérique du Sud'),
('HT','HTI','Haïti','Haiti','Caraïbes'),
('HN','HND','Honduras','Honduras','Amérique centrale'),
('HU','HUN','Hongrie','Hungary','Europe centrale'),
('IN','IND','Inde','India','Asie du Sud'),
('ID','IDN','Indonésie','Indonesia','Asie du Sud-Est'),
('IQ','IRQ','Irak','Iraq','Moyen-Orient'),
('IR','IRN','Iran','Iran','Moyen-Orient'),
('IE','IRL','Irlande','Ireland','Europe occidentale'),
('IS','ISL','Islande','Iceland','Europe du Nord'),
('IL','ISR','Israël','Israel','Moyen-Orient'),
('IT','ITA','Italie','Italy','Europe du Sud'),
('JM','JAM','Jamaïque','Jamaica','Caraïbes'),
('JP','JPN','Japon','Japan','Asie de l''Est'),
('JO','JOR','Jordanie','Jordan','Moyen-Orient'),
('KZ','KAZ','Kazakhstan','Kazakhstan','Asie centrale'),
('KE','KEN','Kenya','Kenya','Afrique de l''Est'),
('KG','KGZ','Kirghizistan','Kyrgyzstan','Asie centrale'),
('KI','KIR','Kiribati','Kiribati','Océanie'),
('KW','KWT','Koweït','Kuwait','Moyen-Orient'),
('LA','LAO','Laos','Laos','Asie du Sud-Est'),
('LS','LSO','Lesotho','Lesotho','Afrique subsaharienne'),
('LV','LVA','Lettonie','Latvia','Europe du Nord'),
('LB','LBN','Liban','Lebanon','Moyen-Orient'),
('LR','LBR','Liberia','Liberia','Afrique subsaharienne'),
('LY','LBY','Libye','Libya','Afrique du Nord'),
('LI','LIE','Liechtenstein','Liechtenstein','Europe occidentale'),
('LT','LTU','Lituanie','Lithuania','Europe du Nord'),
('LU','LUX','Luxembourg','Luxembourg','Europe occidentale'),
('MK','MKD','Macédoine du Nord','North Macedonia','Europe du Sud'),
('MG','MDG','Madagascar','Madagascar','Afrique subsaharienne'),
('MY','MYS','Malaisie','Malaysia','Asie du Sud-Est'),
('MW','MWI','Malawi','Malawi','Afrique subsaharienne'),
('MV','MDV','Maldives','Maldives','Asie du Sud'),
('ML','MLI','Mali','Mali','Afrique subsaharienne'),
('MT','MLT','Malte','Malta','Europe du Sud'),
('MA','MAR','Maroc','Morocco','Afrique du Nord'),
('MH','MHL','Îles Marshall','Marshall Islands','Océanie'),
('MU','MUS','Maurice','Mauritius','Afrique subsaharienne'),
('MR','MRT','Mauritanie','Mauritania','Afrique du Nord'),
('MX','MEX','Mexique','Mexico','Amérique du Nord'),
('FM','FSM','Micronésie','Micronesia','Océanie'),
('MD','MDA','Moldavie','Moldova','Europe de l''Est'),
('MC','MCO','Monaco','Monaco','Europe occidentale'),
('MN','MNG','Mongolie','Mongolia','Asie de l''Est'),
('ME','MNE','Monténégro','Montenegro','Europe du Sud'),
('MZ','MOZ','Mozambique','Mozambique','Afrique subsaharienne'),
('MM','MMR','Myanmar','Myanmar','Asie du Sud-Est'),
('NA','NAM','Namibie','Namibia','Afrique subsaharienne'),
('NR','NRU','Nauru','Nauru','Océanie'),
('NP','NPL','Népal','Nepal','Asie du Sud'),
('NI','NIC','Nicaragua','Nicaragua','Amérique centrale'),
('NE','NER','Niger','Niger','Afrique subsaharienne'),
('NG','NGA','Nigeria','Nigeria','Afrique subsaharienne'),
('NO','NOR','Norvège','Norway','Europe du Nord'),
('NZ','NZL','Nouvelle-Zélande','New Zealand','Océanie'),
('OM','OMN','Oman','Oman','Moyen-Orient'),
('UG','UGA','Ouganda','Uganda','Afrique de l''Est'),
('UZ','UZB','Ouzbékistan','Uzbekistan','Asie centrale'),
('PK','PAK','Pakistan','Pakistan','Asie du Sud'),
('PW','PLW','Palaos','Palau','Océanie'),
('PA','PAN','Panama','Panama','Amérique centrale'),
('PG','PNG','Papouasie-Nouvelle-Guinée','Papua New Guinea','Océanie'),
('PY','PRY','Paraguay','Paraguay','Amérique du Sud'),
('NL','NLD','Pays-Bas','Netherlands','Europe occidentale'),
('PE','PER','Pérou','Peru','Amérique du Sud'),
('PH','PHL','Philippines','Philippines','Asie du Sud-Est'),
('PL','POL','Pologne','Poland','Europe centrale'),
('PT','PRT','Portugal','Portugal','Europe du Sud'),
('QA','QAT','Qatar','Qatar','Moyen-Orient'),
('DO','DOM','République dominicaine','Dominican Republic','Caraïbes'),
('RO','ROU','Roumanie','Romania','Europe de l''Est'),
('GB','GBR','Royaume-Uni','United Kingdom','Europe occidentale'),
('RU','RUS','Russie','Russia','Europe de l''Est'),
('RW','RWA','Rwanda','Rwanda','Afrique de l''Est'),
('KN','KNA','Saint-Kitts-et-Nevis','Saint Kitts and Nevis','Caraïbes'),
('LC','LCA','Sainte-Lucie','Saint Lucia','Caraïbes'),
('VC','VCT','Saint-Vincent-et-les-Grenadines','Saint Vincent and the Grenadines','Caraïbes'),
('SB','SLB','Îles Salomon','Solomon Islands','Océanie'),
('WS','WSM','Samoa','Samoa','Océanie'),
('SM','SMR','Saint-Marin','San Marino','Europe du Sud'),
('ST','STP','Sao Tomé-et-Principe','Sao Tome and Principe','Afrique subsaharienne'),
('SN','SEN','Sénégal','Senegal','Afrique subsaharienne'),
('RS','SRB','Serbie','Serbia','Europe du Sud'),
('SC','SYC','Seychelles','Seychelles','Afrique subsaharienne'),
('SL','SLE','Sierra Leone','Sierra Leone','Afrique subsaharienne'),
('SG','SGP','Singapour','Singapore','Asie du Sud-Est'),
('SK','SVK','Slovaquie','Slovakia','Europe centrale'),
('SI','SVN','Slovénie','Slovenia','Europe du Sud'),
('SO','SOM','Somalie','Somalia','Afrique de l''Est'),
('SD','SDN','Soudan','Sudan','Afrique du Nord'),
('SS','SSD','Soudan du Sud','South Sudan','Afrique subsaharienne'),
('LK','LKA','Sri Lanka','Sri Lanka','Asie du Sud'),
('SE','SWE','Suède','Sweden','Europe du Nord'),
('CH','CHE','Suisse','Switzerland','Europe occidentale'),
('SR','SUR','Suriname','Suriname','Amérique du Sud'),
('SY','SYR','Syrie','Syria','Moyen-Orient'),
('TJ','TJK','Tadjikistan','Tajikistan','Asie centrale'),
('TZ','TZA','Tanzanie','Tanzania','Afrique de l''Est'),
('TD','TCD','Tchad','Chad','Afrique subsaharienne'),
('CZ','CZE','Tchéquie','Czech Republic','Europe centrale'),
('TH','THA','Thaïlande','Thailand','Asie du Sud-Est'),
('TL','TLS','Timor oriental','East Timor','Asie du Sud-Est'),
('TG','TGO','Togo','Togo','Afrique subsaharienne'),
('TO','TON','Tonga','Tonga','Océanie'),
('TT','TTO','Trinité-et-Tobago','Trinidad and Tobago','Caraïbes'),
('TN','TUN','Tunisie','Tunisia','Afrique du Nord'),
('TM','TKM','Turkménistan','Turkmenistan','Asie centrale'),
('TR','TUR','Turquie','Turkey','Asie de l''Ouest'),
('TV','TUV','Tuvalu','Tuvalu','Océanie'),
('UA','UKR','Ukraine','Ukraine','Europe de l''Est'),
('UY','URY','Uruguay','Uruguay','Amérique du Sud'),
('VU','VUT','Vanuatu','Vanuatu','Océanie'),
('VE','VEN','Venezuela','Venezuela','Amérique du Sud'),
('VN','VNM','Viêt Nam','Vietnam','Asie du Sud-Est'),
('YE','YEM','Yémen','Yemen','Moyen-Orient'),
('ZM','ZMB','Zambie','Zambia','Afrique subsaharienne'),
('ZW','ZWE','Zimbabwe','Zimbabwe','Afrique subsaharienne');

SELECT count(*) FROM ref_pays;
